// ScipyLfilterIRTest.cpp
//
// P2-2 — Truly-independent reference test in the time domain.
//
// The earlier scipy golden test (ScipyGoldenResponseTest.cpp) compares the
// engine's measured magnitude response against scipy.signal.freqz, which is
// independent at the math level but doesn't exercise the engine's actual
// difference equation in any "different" way — both sides evaluate the same
// transfer function.
//
// This test is stronger:
//   - Reference: an impulse response generated by scipy.signal.lfilter,
//     which is a compiled Direct Form II implementation. Topology-wise
//     different from our TDF2 inner loop.
//   - Subject:   the engine's actual process() pipeline run on an impulse,
//     reading samples back from the same buffer.
//
// Comparison: per-sample with both an absolute and a relative-amplitude
// tolerance, since float32 round-off accumulates over the IR. We pick
// tolerances that are tight enough to catch real cascade bugs but loose
// enough not to flag legit float32-vs-float64 drift.
//
// Compile (host):
//   cd audio-engine
//   g++ -std=c++17 -O2 -fno-finite-math-only \
//       -I src/main/cpp \
//       -DLFILTER_IR_PATH=\"$(pwd)/src/test/cpp/golden/hd600_lfilter_ir.bin\" \
//       src/test/cpp/ScipyLfilterIRTest.cpp \
//       src/main/cpp/BiquadFilter.cpp \
//       src/main/cpp/AuralTuneEQEngine.cpp \
//       -o /tmp/run_lfilter && /tmp/run_lfilter

#include <cassert>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include "AuralTuneEQEngine.h"

using auraltune::audio::AuralTuneEQEngine;
using auraltune::audio::EqFilterType;

#ifndef LFILTER_IR_PATH
#define LFILTER_IR_PATH "src/test/cpp/golden/hd600_lfilter_ir.bin"
#endif

namespace {

// Tolerances on the impulse-response samples. Float32 cascade vs float64
// scipy gives us ~1e-5 absolute drift at typical sample magnitudes; we pad
// by a factor for accumulated round-off across 2048 IR samples.
constexpr double kAbsTol = 5e-5;
constexpr double kRelTol = 1e-3;   // relative to |scipy_sample|

struct LfilterFixture {
    std::vector<int> rates;
    int irLen = 0;
    // ir[r * irLen + n]
    std::vector<double> ir;
};

bool readWholeFile(const char* path, std::vector<uint8_t>& out) {
    std::ifstream in(path, std::ios::binary);
    if (!in) return false;
    in.seekg(0, std::ios::end);
    const auto sz = in.tellg();
    in.seekg(0, std::ios::beg);
    out.resize(static_cast<size_t>(sz));
    in.read(reinterpret_cast<char*>(out.data()), sz);
    return in.good();
}

// Read one ASCII line from raw bytes starting at pos. Returns the line and
// advances pos past the terminating '\n'.
std::string readLine(const std::vector<uint8_t>& buf, size_t& pos) {
    std::string s;
    while (pos < buf.size() && buf[pos] != '\n') {
        s.push_back(static_cast<char>(buf[pos]));
        ++pos;
    }
    if (pos < buf.size()) ++pos; // skip '\n'
    return s;
}

bool parseFixture(const std::vector<uint8_t>& buf, LfilterFixture& out) {
    size_t pos = 0;
    if (readLine(buf, pos) != "AURALTUNE_LFILTER_IR") return false;
    int nRates = std::atoi(readLine(buf, pos).c_str());
    int irLen  = std::atoi(readLine(buf, pos).c_str());
    if (nRates <= 0 || irLen <= 0) return false;

    {
        std::istringstream is(readLine(buf, pos));
        out.rates.resize(static_cast<size_t>(nRates));
        for (int i = 0; i < nRates; ++i) {
            if (!(is >> out.rates[i])) return false;
        }
    }
    out.irLen = irLen;

    const size_t need = static_cast<size_t>(nRates) * static_cast<size_t>(irLen) * sizeof(double);
    if (pos + need > buf.size()) return false;
    out.ir.assign(static_cast<size_t>(nRates) * irLen, 0.0);
    std::memcpy(out.ir.data(), buf.data() + pos, need);
    return true;
}

void runImpulse(AuralTuneEQEngine& eng, std::vector<float>& outIRStereo, int n) {
    outIRStereo.assign(static_cast<size_t>(n) * 2, 0.0f);
    outIRStereo[0] = 1.0f;
    outIRStereo[1] = 1.0f;
    int rc = eng.process(outIRStereo.data(), n);
    assert(rc == 0);
}

void runForRate(int rate, const double* refIR, int irLen) {
    AuralTuneEQEngine eng(static_cast<double>(rate));
    eng.setAutoEqEnabled(true);

    int   types[3]   = { 1, 0, 2 }; // LowShelf, Peaking, HighShelf
    float freqs[3]   = { 105.0f, 3000.0f, 8000.0f };
    float gains[3]   = { 2.5f, -2.0f, 1.5f };
    float qs[3]      = { 0.7f, 1.0f, 0.7f };
    int rc = eng.updateAutoEq(0.0f, false, 48000.0,
                               types, freqs, gains, qs, 3);
    assert(rc == 0);

    std::vector<float> ir;
    runImpulse(eng, ir, irLen);

    int    failures   = 0;
    int    worstIdx   = -1;
    double worstAbs   = 0.0;
    double worstRel   = 0.0;
    double sumSqDiff  = 0.0;
    double sumSqRef   = 0.0;
    for (int n = 0; n < irLen; ++n) {
        const double engineSample = static_cast<double>(ir[n * 2]); // L channel
        const double refSample    = refIR[n];
        const double diff         = engineSample - refSample;
        const double absErr       = std::fabs(diff);
        const double relErr       = (std::fabs(refSample) > 1e-9)
                                         ? absErr / std::fabs(refSample)
                                         : 0.0;
        sumSqDiff += diff * diff;
        sumSqRef  += refSample * refSample;

        if (absErr > worstAbs) { worstAbs = absErr; worstIdx = n; }
        if (relErr > worstRel) worstRel = relErr;

        if (absErr > kAbsTol && relErr > kRelTol) {
            if (failures < 5) {
                std::printf("  FAIL n=%d ref=%+.6f engine=%+.6f abs=%.2e rel=%.2e\n",
                            n, refSample, engineSample, absErr, relErr);
            }
            ++failures;
        }
    }

    const double snr = (sumSqDiff > 0.0)
                         ? 10.0 * std::log10(sumSqRef / sumSqDiff)
                         : std::numeric_limits<double>::infinity();
    std::printf("  fs=%-6d Hz  worst |Δ| = %.2e  worst rel = %.2e  SNR = %.1f dB  (failures: %d)\n",
                rate, worstAbs, worstRel, snr, failures);
    assert(failures == 0);
}

} // namespace

int main() {
    std::printf("scipy.lfilter IR test — fixture: %s\n", LFILTER_IR_PATH);
    std::vector<uint8_t> raw;
    if (!readWholeFile(LFILTER_IR_PATH, raw)) {
        std::printf("ERROR: could not read fixture\n");
        return 2;
    }
    LfilterFixture fix;
    if (!parseFixture(raw, fix)) {
        std::printf("ERROR: failed to parse fixture\n");
        return 3;
    }
    std::printf("Loaded %zu rates, IR length %d, abs tol %.0e / rel tol %.0e\n",
                fix.rates.size(), fix.irLen, kAbsTol, kRelTol);
    for (size_t i = 0; i < fix.rates.size(); ++i) {
        const double* ref = &fix.ir[i * static_cast<size_t>(fix.irLen)];
        runForRate(fix.rates[i], ref, fix.irLen);
    }
    std::printf("\nscipy.lfilter IR: PASS\n");
    return 0;
}
