// ScipyGoldenResponseTest.cpp
//
// P3-B — Independent reference golden test using a scipy-generated fixture.
//
// This complements GoldenResponseTest.cpp:
//   - GoldenResponseTest derives reference dB values from RBJ formulas in C++.
//     A typo in BOTH the engine and the test would slip through.
//   - This test reads dB values produced by Python scipy.signal.freqz, which
//     is a fully independent numerical implementation. Any divergence here
//     means our RBJ math is wrong (in the engine, in the analytical test, or
//     both — the fixture is the truth).
//
// The fixture lives at audio-engine/src/test/cpp/golden/hd600_oratory1990.json
// and is regenerated by audio-engine/src/test/python/generate_golden.py.
//
// Tolerance: ±0.5 dB at every fixture frequency, per dev-plan Phase 7.
//
// Compile (host):
//   cd audio-engine
//   g++ -std=c++17 -O2 -fno-finite-math-only \
//       -I src/main/cpp \
//       -DGOLDEN_FIXTURE_PATH=\"$(pwd)/src/test/cpp/golden/hd600_oratory1990.json\" \
//       src/test/cpp/ScipyGoldenResponseTest.cpp \
//       src/main/cpp/BiquadFilter.cpp \
//       src/main/cpp/AuralTuneEQEngine.cpp \
//       -o /tmp/run_scipy_golden && /tmp/run_scipy_golden

#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include "AuralTuneEQEngine.h"

using auraltune::audio::AuralTuneEQEngine;
using auraltune::audio::EqFilterType;

#ifndef GOLDEN_FIXTURE_PATH
#define GOLDEN_FIXTURE_PATH "src/test/cpp/golden/hd600_oratory1990.json"
#endif

namespace {

constexpr int kImpulseLen = 16384;
constexpr double kTolerance_dB = 0.5;

struct GoldenPoint {
    double freq;
    double db;
};

struct GoldenForRate {
    int rate;
    std::vector<GoldenPoint> points;
};

// ---------------- Tiny JSON sniffer ----------------
//
// We don't pull a JSON dependency into the host test. The fixture format is
// fixed and small enough that simple textual sniffing is reliable.
//
// We extract:
//   - The list of (rate, [(freq, db), ...]) under "rates": { "<rate>": [[f,d],...] }

bool readWholeFile(const char* path, std::string& out) {
    std::ifstream in(path);
    if (!in) return false;
    std::ostringstream ss; ss << in.rdbuf();
    out = ss.str();
    return true;
}

// Find the next number starting at or after `pos`. Returns the parsed value
// and advances `pos` past it. Skips JSON whitespace and structural chars.
bool nextNumber(const std::string& s, size_t& pos, double& outVal) {
    while (pos < s.size()) {
        char c = s[pos];
        if (c == '-' || (c >= '0' && c <= '9')) break;
        ++pos;
    }
    if (pos >= s.size()) return false;
    size_t start = pos;
    while (pos < s.size()) {
        char c = s[pos];
        if ((c >= '0' && c <= '9') || c == '-' || c == '+' || c == '.' || c == 'e' || c == 'E') {
            ++pos;
        } else break;
    }
    try {
        outVal = std::stod(s.substr(start, pos - start));
        return true;
    } catch (...) { return false; }
}

bool parseFixture(const std::string& doc, std::vector<GoldenForRate>& outAll) {
    // Look for "rates":
    size_t rPos = doc.find("\"rates\"");
    if (rPos == std::string::npos) return false;
    rPos = doc.find('{', rPos);
    if (rPos == std::string::npos) return false;
    ++rPos;

    while (rPos < doc.size()) {
        // Skip whitespace
        while (rPos < doc.size() && (doc[rPos] == ' ' || doc[rPos] == '\n' ||
                                      doc[rPos] == '\r' || doc[rPos] == '\t' ||
                                      doc[rPos] == ',')) ++rPos;
        if (rPos >= doc.size() || doc[rPos] == '}') break;
        if (doc[rPos] != '"') return false;

        // Parse rate key.
        ++rPos;
        size_t keyEnd = doc.find('"', rPos);
        if (keyEnd == std::string::npos) return false;
        int rate = std::atoi(doc.substr(rPos, keyEnd - rPos).c_str());
        rPos = keyEnd + 1;

        // Find the array.
        size_t arrStart = doc.find('[', rPos);
        if (arrStart == std::string::npos) return false;
        // Match the closing bracket of THIS array.
        int depth = 0;
        size_t arrEnd = arrStart;
        for (size_t i = arrStart; i < doc.size(); ++i) {
            if (doc[i] == '[') ++depth;
            else if (doc[i] == ']') {
                if (--depth == 0) { arrEnd = i; break; }
            }
        }
        if (arrEnd == arrStart) return false;

        // Parse [[f,d],[f,d],...] inside.
        GoldenForRate g; g.rate = rate;
        size_t innerPos = arrStart + 1;
        while (innerPos < arrEnd) {
            size_t openInner = doc.find('[', innerPos);
            if (openInner == std::string::npos || openInner > arrEnd) break;
            size_t closeInner = doc.find(']', openInner + 1);
            if (closeInner == std::string::npos || closeInner > arrEnd) break;

            size_t pp = openInner + 1;
            double f = 0, d = 0;
            if (!nextNumber(doc, pp, f)) break;
            if (!nextNumber(doc, pp, d)) break;
            g.points.push_back({f, d});
            innerPos = closeInner + 1;
        }
        outAll.push_back(g);
        rPos = arrEnd + 1;
    }
    return true;
}

// ---------------- Engine measurement ----------------

double dftMagnitudeAtFrequency(const float* mono, int N, double f, double fs) {
    double real = 0.0, imag = 0.0;
    const double k = -2.0 * M_PI * f / fs;
    for (int n = 0; n < N; ++n) {
        const double angle = k * n;
        real += mono[n] * std::cos(angle);
        imag += mono[n] * std::sin(angle);
    }
    return std::sqrt(real * real + imag * imag);
}

double engineDb(AuralTuneEQEngine& eng, double f, double fs) {
    std::vector<float> ir(kImpulseLen * 2, 0.0f);
    ir[0] = 1.0f; ir[1] = 1.0f;
    eng.process(ir.data(), kImpulseLen);

    std::vector<float> mono(kImpulseLen);
    for (int i = 0; i < kImpulseLen; ++i) mono[i] = ir[i * 2];

    const double mag = dftMagnitudeAtFrequency(mono.data(), kImpulseLen, f, fs);
    if (mag <= 1e-30) return -300.0;
    return 20.0 * std::log10(mag);
}

void runForRate(int rate, const std::vector<GoldenPoint>& expected) {
    AuralTuneEQEngine eng(static_cast<double>(rate));
    eng.setAutoEqEnabled(true);

    int   types[3]   = { 1, 0, 2 }; // LowShelf, Peaking, HighShelf
    float freqs[3]   = { 105.0f, 3000.0f, 8000.0f };
    float gains[3]   = { 2.5f, -2.0f, 1.5f };
    float qs[3]      = { 0.7f, 1.0f, 0.7f };

    int rc = eng.updateAutoEq(0.0f, false, 48000.0,
                               types, freqs, gains, qs, 3);
    assert(rc == 0);

    int failures = 0;
    double worstAbsErr = 0.0;
    double worstFreq = 0.0;
    for (const auto& gp : expected) {
        if (gp.freq >= rate / 2.0) continue;
        const double measured = engineDb(eng, gp.freq, rate);
        const double err = measured - gp.db;
        const double absErr = std::fabs(err);
        if (absErr > worstAbsErr) { worstAbsErr = absErr; worstFreq = gp.freq; }
        if (absErr > kTolerance_dB) {
            ++failures;
            std::printf("  FAIL @ %.0f Hz : scipy=%.4f engine=%.4f Δ=%.4f\n",
                        gp.freq, gp.db, measured, err);
        }
    }
    std::printf("  fs=%-6d Hz  worst |Δ| = %.4f dB at %.0f Hz  (%d failures)\n",
                rate, worstAbsErr, worstFreq, failures);
    assert(failures == 0);
}

} // namespace

int main() {
    std::printf("Scipy golden response test — fixture: %s\n", GOLDEN_FIXTURE_PATH);

    std::string doc;
    if (!readWholeFile(GOLDEN_FIXTURE_PATH, doc)) {
        std::printf("ERROR: could not read fixture '%s'\n", GOLDEN_FIXTURE_PATH);
        return 2;
    }
    std::vector<GoldenForRate> all;
    if (!parseFixture(doc, all) || all.empty()) {
        std::printf("ERROR: failed to parse fixture\n");
        return 3;
    }
    std::printf("Loaded %zu rate sets, tolerance ±%.2f dB\n", all.size(), kTolerance_dB);
    for (const auto& g : all) {
        runForRate(g.rate, g.points);
    }
    std::printf("\nScipy golden response: PASS\n");
    return 0;
}
